services:
  - type: web
    name: server
    env: node
    plan: free
    autoDeploy: yes
    buildCommand: "pnpm --filter server build && cd apps/server && pnpm exec prisma generate"
    startCommand: "pnpm --filter server start"
    envVars:
      - key: NODE_ENV
        value: production
