
services:
  - type: web
    name: server
    env: node
    plan: free
    autoDeploy: yes
    buildCommand: "pnpm install --prod && pnpm --filter server build"
    startCommand: "pnpm --filter server start"
    envVars:
      - key: NODE_ENV
        value: production
